$("#response").hide();
$("#version").text("develop").css("font-weight", "600");
$("#modal-ativacao").hide();
$("#resultado-busca").hide();
$("#idLoja2").hide();
$("#listarComparacao").hide();
$("#resultado1").hide();
$("#resultado2").hide();
$("#resultado3").hide();
$("#resultado4").hide();
